version: 2.1
commands:
  print_pipeline_id:
    description: "command to print circleci workflow id"
    parameters:
      project_name:
        type: string
        default: "train booking"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID in project << parameters.project_name >>

orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  print_workflow:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - print_pipeline_id
      - run: bash 'return 1'
      - run:
          name: 'Run on fail'
          command: echo 'Project failed'
          when: on_fail 
workflows:
  version: 1
  one_and_two:
    jobs:
      - print_workflow
      
