version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: echo 'Money flows to me easily and effortlessly' > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
workflows:
  version: 1
  one_and_two:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
