version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  print_hello:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: echo 'hello'
  print_name:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
            command: |
              echo $PROJECT_OWNER
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
workflows:
  version: 1
  one_and_two:
    jobs:
      - print_hello
      - print_name:
          requires:
            - print_hello
